[package]
name = "cohoard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
pulldown-cmark = "0.9.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
tera = "1.16.0"
