name: Publish New Cohoard Version

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'The version of the WASM binary. This determines the name of the folder that will be uploaded to.'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wasm
    steps:
    - uses: actions/checkout@v3
    - name: Download and Set Up
      run: |
           rustup default nightly
           curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Print Info
      run: pwd && ls && rustup show
    - name: Build and Pack
      run: |
           wasm-pack build --target web --release
           wasm-pack pack
    - name: Publish
      run: |
           cd pkg
           mkdir ${{ inputs.versionName }}
           mv cohoard.js ${{ inputs.versionName }}
           mv cohoard_bg.wasm ${{ inputs.versionName }}
           cd ${{ inputs.versionName }} && pwd && ls
           echo "Publishing cohoard.js and cohoard_bg.wasm..."